### ISSUE TITLE
Cant save when starting with webhook

### ISSUE THREAD

**Issue by Azathoth88** [dopplertask/dopplertask#15]
I have tried to testing the Webhook-Parameter. When I start with the webhook parameter, I cannot save the task. I always seem to have to use "StartAction". Then the saving works. However, I understand that the webhook call should work without this function, right?

Example:
https://i.imgur.com/4vp4iRi.png

**Comment by feraswilson** [comment]
To use the Webhook trigger, you need to set Activated Triggers to true on the side menu. You can keep the StartAction unconnected.

**Comment by Azathoth88** [comment]
Okay, you have to know that. Are there cases where this is not needed? Otherwise, from the user's point of view, it would make the most sense to prevent the deletion of the StartAction.

At the very least, I would expect an error message: "Your task is faulty and therefore cannot be saved.
Currently nothing happens. Which is a little unsettling.

**Comment by feraswilson** [comment]
I agree, will look into a solution for this.
