### ISSUE TITLE
Pass data from webhook (Array) in INSERT INTO

### ISSUE THREAD

**Issue by Azathoth88** [dopplertask/dopplertask#16]
I hope I'm not annoying....
Things are getting exciting now. The webhook is running and can be accessed via my reverse proxy.

I had already written that I would like to access the member database via our association homepage.
Unfortunately, I am far away from being a developer and therefore need support. Professionally, I am only a product owner - at least I can give you feedback for your great software-project. 

Maybe you can have a look here.
I use the following Wordpress plugin:
https://pafe.piotnet.com/docs/webhook/

When I submit a contact form, the webhook can be accessed.
How do I get the data from the array into my MySQL INSERT? Can I include the data from the array in the SQL query?

Does something like this work (pseudo code) - refers to the description of piotnet

INSERT INTO test (test1,test2,test3) VALUES ('[first_name]','[last_name]','[email]')

best regards from Berlin

**Comment by feraswilson** [comment]
You can use Javascript to first parse the JSON. So something like this (Psuedo): 
```
var myJson = JSON.parse(yourJSON);
for(var i = 0; i < myJson["fields"].length; i++) {
    var obj = json[i];

    console.log(obj["value"]);
}
```

Once you have the values, then do like you suggested with the insert. 

If you need help with it, I can take a look with you on the matter.

**Comment by feraswilson** [comment]
INSERT and UPDATE are now supported in the MySQL Action

**Comment by Azathoth88** [comment]
I finally found some time today to take a closer look at the topic. The basic INSERT now works (at least when the MySQL action is set to VELOCITY). 

With JavaScript I get the message: "org.graalvm.polyglot.PolyglotException: ReferenceError: mysql2ff2 is not defined" - This could be a new bug of version 0.14.6.

Back to the actual topic. I still want to trigger a webhook via a contact form in wordpress and write the data into a separate MySQL database.
I am, as described above, to the point where I can webhook hardcoded data into the database. I'm a bit overwhelmed with the rest for now, as I'm not a programmer.

Is there any possibility that you can provide a sample config?
At best with a ready-made parsing script?

Many thanks for your efforts and best regards

**Comment by feraswilson** [comment]
Do you mind exporting your workflow as JSON and database (if needed) for me to test?

**Comment by Azathoth88** [comment]
I can build my test scenario with demo data.
How could I submit the data? I would not like to post this unprotected in Github.

**Comment by feraswilson** [comment]
Send it to my email: info@dopplertask.com
