### ISSUE TITLE
Script Generation

### ISSUE THREAD

**Issue by b4b857f6ee** [dopplertask/dopplertask#22]
Hello,

I was wondering if you can imagine generate script so you can run the task configure to another desktop like we can do with actionaz ?
And add keyboard action :D. This could be awesome!

Any way your product is very cool :).

**Comment by feraswilson** [comment]
I found it very interesting. As we build actions, we need to think about how an action can work in any environment and not just in one specific OS. We can absolutely do that, and as you can see, we already have a mouse action. So a Keyboard action is a very good suggestion. :) I saw that there are other actions too, which I also think are valuable. 

Thanks for your suggestion, and we will have a look on how we can implement these actions! Support this project by giving it a star :)

If you need help or info, let me know :)

**Comment by b4b857f6ee** [comment]
Yes, very nice.
I'm using actionaz for automation for attack/defense exercice and the dopplertask look like a SOAR interface ahah.
So this is really really cool!
I would love to help but i'm not a dev x'D...
Thank you for your quick answer.
Your GUI is nice (like very). Maybe some info in actionaz can help you to add action or idea.
On my side i'm using like only keyboard because you don't know if people are going to change the screen resolution so i'm doing all by keyboard. Less mistake ^^.
I forgot the star you right! I've already send your projet on many discord or colleague because this look awesome :D 
At first i was thinking "A revolutionary open-source automation tool " revolutionary? Really? And i look at your GUI "Ok, that's kind of very cool :)"
Anyway your project can help IT work and Cyber Security exercice.
Building autonomous script or .exe like actionaz for Linux or Windows, this can be next level and maybe the actionaz github can inspire you go do it more easier.
I know people use Ansible and it's awesome. We are more command line people ahah, but having this kind of GUI... This is the next level to be able to make it easier to anyone. And you wrote it : "The future is higher level no-code mindset" ;)
Well, very good project!
Keep it up!

**Comment by feraswilson** [comment]
Awesome, thanks for the support! Let's begin the journey to the future of how we do things, starting in IT!
