### ISSUE TITLE
INSERT INTO MySQL / MariaDB

### ISSUE THREAD

**Issue by Azathoth88** [dopplertask/dopplertask#7]
Hello, I just became aware of your software. I find it exciting. I am currently checking whether I can possibly use it for our club homepage. Use case: When a new membership application is received via the website, the data should be automatically entered into the member database (MySQL). Via the contact form in wordpress I can in principle control a webhook.

Now I wanted to test an INSERT INTO - the following query: 
INSERT INTO test (test1,test2,test3) VALUES ('1','2','3')

But I get the message:
Action execution result:
java.sql.SQLException: Can not issue data manipulation statements with executeQuery().

The query SELECT * FROM test works.
Action execution result:
Quering: SELECT * FROM test
Result: 

1 test1, 2 test2, 3 test3
1 test1, 2 test2, 3 test3
1 test1, 2 test2, 3 test3

What is wrong here?

**Comment by feraswilson** [comment]
Hi,

Thanks for notifying me about this. Yeah, at the current time, you can only get data, not manipulate it. I will definitely add what you are looking for in the coming day or two so you can use it.

I will keep this open until the solution is in-place.
Thanks,

**Comment by feraswilson** [comment]
@Azathoth88 The latest push at this time of writing (0.11.1) contains the fixes for your issue. Hope this helpes!
If this doesn't fix your issue, please reopen the issue and we can have a further look.

**Comment by Azathoth88** [comment]
Hello - Thank you for the adjustment. Unfortunately, it still doesn't work.
I used the image dopplertask/dopplertask:0.11.1.

Attached are two screenshots:
https://i.imgur.com/V15zmDo.png - working SELECT-Statement
https://i.imgur.com/bSHotKh.png - not working INSERT-Statement

I don't know if it's only a small syntax error. Anyway, the 1:1 from phpMyAdmin doesn't work.

@feraswilson I can't reopen.

**Comment by feraswilson** [comment]
Try to remove the docker image locally and repull the image. I updated the image just now.

**Comment by Azathoth88** [comment]
I have already deleted the image and pulled it again.
See my screen from portainer: https://i.imgur.com/Ho82hfY.png

Is it possible that the changes are not pulled from the dockerhub?

**Comment by feraswilson** [comment]
Interesting, I will have a look soon and see if I am also getting an old version. Because if you look at the code, you can see that I’m no longer using executeQuery.

**Comment by feraswilson** [comment]
I tried again and it's working, check that your DopplerTask container digest is: DIGEST:sha256:27b5f67c056d5e9b5e38fbc16a28b69644aff428930204f38f922ff651a30d2e

Try again, also try running it on your own computer and see if it connects.

**Comment by feraswilson** [comment]
If the issue persists, please comment or create a new issue.
